## CircleCI configuration - see https://circleci.com/docs/2.0/configuration-reference/
version: 2.1

anchors:
  container-config: &container-config
      docker:
        - image: circleci/python:3.7.2

  only-master: &only-master
    filters:
      branches:
        only: master

jobs:
  test:
    <<: *container-config
    steps:
      - checkout
      - run:
          name: Install Tox
          command: sudo pip install tox
      - run:
          name: Run Tox Tests
          command: tox
  deploy-to-pypi:
    description: Deploy the package to PYPI
    <<: *container-config
    steps:
      - checkout
      - run: 
          name: install s3pypi
          command: sudo pip install s3pypi
      - run:
          name: Deploy services
          command: |
            s3pypi --bucket deg-shared-services-pypi-us-east-1 --private --secret ${S3PYPI_SECRET}
          
workflows:
    version: 2
    test-deploy:
      jobs:
        - test:
            name: test
            context: deg-testing

        - deploy-to-pypi:
            name: deploy package to pypi
            <<: *only-master
            context: aws-data-shared-services
            requires: [test]
